### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Bryan2Chow** [yuanxiaosc/Entity-Relation-Extraction#52]
Hi, thanks for your work!
I get an error as  follow when  I excuted evaluate_classifiction.py  
------------------------------------------------
Traceback (most recent call last):
  File "evaluate_classifiction.py", line 51, in <module>
    assert len(golden_data) == len(predict_data)
**AssertionError**
----------------------------------------------
and I checked golden_data file(predicate_out.txt),including 1000 rows
![image](https://user-images.githubusercontent.com/42020225/84032626-353e8880-a9ca-11ea-9e9e-5dac1f6687ed.png)
However, the predict_data (predicate_predict.txt) only have 500 rows
![image](https://user-images.githubusercontent.com/42020225/84032578-235ce580-a9ca-11ea-8afc-0d7f8ccfcbab.png)
Could you please tell me what part of the process went wrong? and how to fix it?
I am very pleased to hear from you on the question's comments.

**Comment by yuanxiaosc** [comment]
@Bryan2Chow 
I'm sorry, I'm only seeing this now. The logic of evaluate_ classifiction.py is to obtain the file name that the standard answer and model prediction answer are stored firstly, then obtain the file content according to the file name, then check whether the file content is legal (such as whether the number of lines is consistent), and then conduct other statistics.
This error is probably caused by the error in the function to get the file name. You can modify the function or specify the file name to be compared manually, that is, change the following function call to the file name specified manually.

40 and 43 code lines!
+ predicate_ predict_ file_ path = get_ latest_ model_ predict_ data_ path()
+ golden_ file_ path = get_ golden_ file_ path()

**Comment by Jerryten** [comment]
i also meet this problem and i want to know how to sovle . i do not know how to revise the code
